### ISSUE TITLE
Current style issues as per `npx standard`

### ISSUE THREAD

**Issue by ImpregnableProgrammer** [CSE115AWinter2022-WePee/WePee#20]
Style issues after running `npx standard –fix` as of 3/10 12:15 PM

This is being tracked in [this](https://docs.google.com/document/d/1NgOVBVgoTaAuFYgU7kmgfWMaGiy75YJIXGiScozAgZE/edit?usp=sharing) Google doc

**Comment by ImpregnableProgrammer** [comment]
Many of the style issues have been fixed now, with those remaining only due to the database naming scheme. Field names were intentionally different from camelCase (our style convention) for easy database and code differentiation.

**Comment by dekramer-business** [comment]
Rohan's comment above still holds true. The below are the current syling errors:

- modules\getAndSetBathroomNameFromId.js:5:45: Identifier 'bathroom_id' is not in camel case. (camelcase)
- modules\getAndSetBathroomNameFromId.js:19:50: Identifier 'review_id' is not in camel case. (camelcase)
- screens\addBathroom.js:110:13: Identifier 'review_id' is not in camel case. (camelcase)
- screens\addBathroom.js:111:13: Identifier 'review_data' is not in camel case. (camelcase)
- screens\addBathroom.js:115:13: Identifier 'review_id' is not in camel case. (camelcase)
- screens\bathroomDetails.js:85:15: Identifier 'user_name' is not in camel case. (camelcase)
- screens\bathroomDetails.js:85:26: Identifier 'bathroom_name' is not in camel case. (camelcase)
- screens\bathroomDetails.js:85:41: Identifier 'bathroom_id' is not in camel case. (camelcase)
- screens\bathroomDetails.js:86:11: Identifier 'bath_name' is not in camel case. (camelcase)
- screens\bathroomDetails.js:86:23: Identifier 'bathroom_name' is not in camel case. (camelcase)
- screens\bathroomDetails.js:87:22: Identifier 'user_name' is not in camel case. (camelcase)
- screens\bathroomDetails.js:88:12: Identifier 'bath_name' is not in camel case. (camelcase)
- screens\bathroomDetails.js:89:9: Identifier 'bath_name' is not in camel case. (camelcase)
- screens\bathroomDetails.js:96:37: Identifier 'bath_name' is not in camel case. (camelcase)
- screens\bathroomDetails.js:96:52: Identifier 'bathroom_id' is not in camel case. (camelcase)
- screens\profilePage.js:43:15: Identifier 'bathroom_name' is not in camel case. (camelcase)
- screens\profilePage.js:43:30: Identifier 'bathroom_id' is not in camel case. (camelcase)
- screens\profilePage.js:44:18: Identifier 'bathroom_name' is not in camel case. (camelcase)
- screens\profilePage.js:49:26: Identifier 'bathroom_id' is not in camel case. (camelcase)
